openapi: 3.0.3

info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.0
servers:
  - url: http://localhost:8080

tags:
  - name: order
    description: Everything about order

paths:
  /order/list:
    $ref: ./paths/list.yaml
  /order/create:
    $ref: ./paths/create.yaml
  /order/{id}:
    $ref: ./paths/detail.yaml
  /order/{id}/update:
    $ref: ./paths/update.yaml